version: "3.9"

services:
  upload:
    build: .
    container_name: tp2-upload
    volumes:
      - ./data:/app/data         
    environment:
      - LOG_LEVEL=info
      - DATA_DIR=/app/data
      - CSV_PATH=/app/data/artigo.csv
    command: ["./bin/upload", "/app/data/artigo.csv"]

  findrec:
    build: .
    container_name: tp2-findrec
    volumes:
      - ./data:/app/data
    environment:
      - LOG_LEVEL=info
      - DATA_DIR=/app/data
    command: ["./bin/findrec", "123"]   

  seek1:
    build: .
    container_name: tp2-seek1
    volumes:
      - ./data:/app/data
    environment:
      - LOG_LEVEL=info
      - DATA_DIR=/app/data
    command: ["./bin/seek1", "123"]

  seek2:
    build: .
    container_name: tp2-seek2
    volumes:
      - ./data:/app/data
    environment:
      - LOG_LEVEL=info
      - DATA_DIR=/app/data
    command: ["./bin/seek2", "Spatially-multiplexed MIMO markers."]
